### ISSUE TITLE
Is it possible to run Ionad on-demand?

### ISSUE THREAD

**Issue by Lindsey1986** [Fody/Ionad#63]
I'm evaluating if Fody + Ionad is an option for a project I'm building, and that would require me to write a small console app that I can pass some assembly file paths and then run Fody + Ionad to perform some replacements of static function calls on these assemblies.

Is this a supported scenario for Fody & Ionad? Any pointers on how to go about it?

**Comment by SimonCropp** [comment]
currently no it is not possible. fody can only be run the the context of MSBuild.

havnt looked into how to go about it

**Comment by Lindsey1986** [comment]
Thank you @SimonCropp! Is there an alternative way of doing what I need using MSBuild?

I'm able to run Ionad replacements on my own code, but I don't know how I can run it on other assemblies - even the ones that I reference directly.

Is there a way to give Fody/Ionad additional assemblies other than the ones that are generated from my project during build?

**Comment by SimonCropp** [comment]
> I'm able to run Ionad replacements on my own code, but I don't know how I can run it on other assemblies - even the ones that I reference directly.

Why would you want to do that?

> Is there a way to give Fody/Ionad additional assemblies other than the ones that are generated from my project during build?

no

**Comment by Lindsey1986** [comment]
I'd like to replace static calls across my entire application, which is never just _my_ code. i.e. If I replace calls to `DateTime.Now` in my code, I also want to replace calls made in other libraries that I depend on.

**Comment by tom-englert** [comment]
You could just write a simple app that uses https://github.com/Fody/Fody/blob/master/FodyIsolated and feeds it with everything you need.

**Comment by Lindsey1986** [comment]
Thank you @tom-englert I'll give that a shot!
