### ISSUE TITLE
Ionad does not support method overloading

### ISSUE THREAD

**Issue by arontsang** [Fody/Ionad#67]
Ionad always picks up the FIRST method overload with the correct name, and does not implement overloading resolution correctly.

In the below example we get an `InvalidProgramException`. But if you swap the order of declaration of the two overloads of TaskRx.Delay, the program runs.

```
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            await Task.Delay(100000);
            return 0;
        }

    }

    [StaticReplacement(typeof(Task))]
    public static class TaskRx
    {

        public static Task Delay(int delay, CancellationToken cancellationToken)
        {
            return Observable.Timer(TimeSpan.FromMilliseconds(delay)).ToTask(cancellationToken);
        }

        public static Task Delay(int delay)
        {
            return Observable.Timer(TimeSpan.FromMilliseconds(delay)).ToTask();
        }
    }
```

**Comment by arontsang** [comment]
Found the issue.

CecilExtensions:67 ReferenceMethod(this TypeReference typeRef, string methodName) is wrong. We also need to pass in the Parameter types.

It also seems like this method would fail for Generic methods.

I would create a PR to fix this code, but my company only allows RO access to Github.

**Comment by SimonCropp** [comment]
@arontsang on the company note. based on this requirement https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#organization-licensing am i safe in assuming you are the only developer at your company?

**Comment by arontsang** [comment]
@SimonCropp No I am not the only developer at my company.
I am trying to bring in Fody to our company, $3 per month per dev is not much at all...but conversely it could take time. We would be bringing in Fody to replace PostSharp.

I am paying out of pocket, which I don't mind for myself, partly because I have used Fody in the past for many project (I think before the patron thing started).

I've got a good handle on the bug itself, and I could try to put together a PR this weekend (assuming the home boss allows it).

**Comment by arontsang** [comment]
PR raised.

https://github.com/Fody/Ionad/pull/68

I would really appreciate it if you could also backport it to 1.0.2

Thank you

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by arontsang** [comment]
Thanks Simon, I might put together a PR now for preventing recursive calls,
similar to PR 4 https://github.com/Fody/Ionad/pull/4.

Basically if FooReplace.Bar calls Foo.Bar, Fody.Ionad should not replace
that call, since FooReplace can call FooReplace directly when needed.
